on : push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Static Analysis Tools
      run: | 
          autopep8 hw2_debugging.py > post_traces/autopep8_hw2_debugging_trace.txt
          pylint hw2_debugging.py > post_traces/pylint_hw2_debugging_trace.txt
          pyright hw2_debugging.py > post_traces/pyright_hw2_debugging_trace.txt
          autopep8 rand.py > post_traces/autopep8_rand_trace.txt
          pylint rand.py > post_traces/pylint_rand_trace.txt
          pyright rand.py > post_traces/pyright_rand_trace.txt

